import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={cn("bg-background min-h-screen font-sans antialiased")}>
        <div className="bg-background relative flex min-h-screen flex-col">
          <main className="container flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
